version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: cesarcruzc/parque_automotor
    volumes:
     - .:/var/www/html
    ports:
     - "${APP_PORT}:80"
    networks:
     - develop
networks:
  develop:
    driver: "bridge"