<?php 
return [
'cnf_appname' 			=> 'Parque Automotor',
'cnf_appdesc' 			=> 'Parque Automotor',
'cnf_comname' 			=> 'Alcaldía de Soacha',
'cnf_email' 			=> 'cc.cruz.caceres@gmail.com',
'cnf_metakey' 			=> 'my site , my company  , Larvel Crud',
'cnf_metadesc' 		=> 'Write description for your site',
'cnf_group' 			=> '3',
'cnf_activation' 		=> 'confirmation',
'cnf_multilang' 		=> '0',
'cnf_lang' 			=> 'en',
'cnf_regist' 			=> 'false',
'cnf_front' 			=> 'false',
'cnf_recaptcha' 		=> 'false',
'cnf_theme' 			=> 'default',
'cnf_backend' 			=> 'sximo5',
'cnf_recaptchapublickey' => '',
'cnf_recaptchaprivatekey' => '',
'cnf_mode' 			=> 'production',
'cnf_logo' 			=> 'backend-logo.png',
'cnf_allowip' 			=> '',
'cnf_restrictip' 		=> '192.116.134 , 194.111.606.21 ',
'cnf_mail' 			=> 'swift',
'cnf_maps' 			=> '',
'cnf_date' 			=> 'Y-m-d',
];
